workflow:
   name: "Kernel Experiment Workflow Test"
   modules:

   - module:
      name: RDFDataSet
      source: org.data2semantics.exp.modules.RDFDataSetModule
      inputs:
         filename: "C:\\Users\\Gerben\\Dropbox\\data_bgs_ac_uk_ALL"
         mimetype: "text/plain"
      
   - module:
      name: GeoDataSet
      source: org.data2semantics.exp.modules.GeoDataSetModule
      inputs: 
         dataset:
            reference: RDFDataSet.dataset
         minSize: 10
         fraction: 0.01
         seed: [11, 21, 31]
         property: "http://data.bgs.ac.uk/ref/Lexicon/hasTheme"
         
   - module:
      name: LibLINEARParms
      source: org.data2semantics.exp.modules.LibLINEARParmsModule
      inputs:
         cs: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
         splitFraction: 0.7
         target:
            reference: GeoDataSet.target
            
   - module: 
      name: RDFWLSubTreeKernel
      source: org.data2semantics.exp.modules.RDFWLSubTreeKernelModule
      inputs:
         iterations: [0, 2, 4]
         depth: [1, 2]
         inference: true
         normalize: true
         reverse: false
         dataset:
            reference: RDFDataSet.dataset
         instances:
            reference: GeoDataSet.instances
         blacklist:
            reference: GeoDataSet.blacklist
            
            
   - module: 
      name: RDFIntersectionTreeEdgeVertexPathKernel
      source: org.data2semantics.exp.modules.RDFIntersectionTreeEdgeVertexPathKernelModule
      inputs:
         depth: [1, 2]
         probabilities: false
         inference: true
         normalize: true
         dataset:
            reference: RDFDataSet.dataset
         instances:
            reference: GeoDataSet.instances
         blacklist:
            reference: GeoDataSet.blacklist
            
         
   - module:
      name: Experiment
      source: org.data2semantics.exp.modules.ExperimentModule
      inputs:
         featureVectors:         
              reference: RDFWLSubTreeKernel.featureVectors
              # - reference: RDFIntersectionTreeEdgeVertexPathKernel.featureVectors
         target:
            reference: GeoDataSet.target
         parms:
            reference: LibLINEARParms.parameters
         seed: 111
         folds: 5
      
